config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "categories#index"
  resources :categories do
    resources :bookmarks
  end
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :recipe_id, presence: true
  validates :category_id, presence: true
  validates :comment, length: { minimum: 6 }
  validates :recipe, uniqueness: { scope: :category }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, presence: true, uniqueness: true

  CATEGORY_IMAGES = [ "https://plus.unsplash.com/premium_photo-1669150852127-2435412047f2?q=80&w=2017&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://images.unsplash.com/photo-1503011994592-d30eb1ef61dc?q=80&w=2006&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://plus.unsplash.com/premium_photo-1699976106749-6639d0986e9b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://plus.unsplash.com/premium_photo-1679434184867-a294eb85400c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://plus.unsplash.com/premium_photo-1672363353881-68c8ff594e25?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://plus.unsplash.com/premium_photo-1678897742200-85f052d33a71?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://images.unsplash.com/photo-1478998674531-cb7d22e769df?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://plus.unsplash.com/premium_photo-1700746099630-66c656bf8236?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://images.unsplash.com/photo-1495480137269-ff29bd0a695c?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://plus.unsplash.com/premium_photo-1671403964040-3fa56d33f44b?q=80&w=2002&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://plus.unsplash.com/premium_photo-1673108852141-e8c3c22a4a22?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" ]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  has_many :categories, through: :bookmarks

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :meal_id, uniqueness: true, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_category

  def new
    @bookmark = Bookmark.new
    @recipes = Recipe.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category

    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@category), status: :see_other
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.image_url = CATEGORY_IMAGES.sample

    if @category.save
      redirect_to category_path(@category), notice: "Category was successfully created."
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @recipe = @category.recipes
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, status: :see_other
  end

  private


  def category_params
    params.require(:category).permit(:name, :image_url)
  end
end

app/controllers/recipe_controller.rb
class RecipesController < ApplicationController
  def index
    if params[:category_id]
      @recipes = Recipe.where(category_id: params[:category_id])
    else
      @recipes = Recipe.all
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    if params[:category_id]
      @recipes = Recipe.where(category_id: params[:category_id])
    else
      @recipes = Recipe.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/bookmarks/_bookmark.html.erb
<div class="polite-card" id="bookmark-card">
    <img src="<%= bookmark.recipe.image_url %>" class="card-img-top-bookmark" alt="<%= bookmark.recipe.name %>">
        <div class="css-card">
            <%= link_to bookmark.recipe.name, class: "card-title" %>
             <p class="card-text" style="margin-bottom: -5px; margin-top: 20px"><strong>Rating:</strong> <%= bookmark.recipe.rating %></p>
             <p class="card-text"><strong>Comment:</strong> <%= bookmark.comment %></p>
            <%= link_to 'Delete', category_bookmark_path(@category, bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm" %>
        </div>
</div>

app/views/bookmarks/new.html.erb
<%= simple_form_for [@category, @bookmark] do |f| %>
  <div class="container p-5">
    <div class="card-header mt-3" style="padding-left: 20px; padding-top: 20px">
      <h2>Add a Bookmark</h2>
      <%= link_to 'Back', categories_path, class: "btn btn-outline-secondary float-right", :style=>"width: 100px; margin-right: 20px; margin-bottom: 5px;"%>

    </div>
    <div class="card-body">
      <%= f.association :recipe %>
      <%= f.input :comment, label: "Comment" %>
      <%= f.button :submit, class: "btn btn-primary btn btn-primary btn-lg btn-block crispy-fill" %>
    </div>
  </div>
<% end %>

app/views/bookmarks/show.html.erb
<div class="card">
  <div class="card-header">
    <h2><%= @category.name %></h2>
  </div>
  <div class="card-body">
    <ul>
      <%= render partial: 'bookmarks/bookmark', collection: @category.bookmarks %>
    </ul>
  </div>
  <div class="card-footer">
    <%= link_to 'New Bookmark', new_category_bookmark_path(@category), class: "btn btn-primary" %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container moody">
  <div class="banner mt-2">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg" alt="Banner Image" class="banner-image">  
    <h1 style="padding: 12px;">Welcome to your Personal Cookbook</h1>
  </div>
  <div class="card-container">
    <% @categories.each do |category| %>
      <div class="polite-card mt-4">
        <div class="card-header-index">
          <%= link_to category.name, category %>
          <%= link_to category do %>
            <img src="<%= category.image_url %>" class="card-img-top" alt="<%= category.name %>">
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-end mt-2">
    <%= link_to 'New Category', new_category_path, class: "btn btn-primary btn-lg btn-block crispy-fill" %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container p-5">
  <div class="card-header mt-3" style="padding-left: 20px; padding-top: 20px">
    <h2>New Category</h2>
    <%= link_to 'Back', categories_path, class: "btn btn-outline-secondary float-right", :style=>"width: 100px; margin-right: 20px; margin-bottom: 5px;"%>
  </div>
  <div class="card-body">
    <%= simple_form_for @category do |f| %>
      <%= f.input :name %>
      <%= f.button :submit, class: "btn btn-primary btn btn-primary btn-lg btn-block crispy-fill" %>
    <% end %>
  </div>
  <div class="card-footer">
    
  </div>
</div>

app/views/categories/show.html.erb
<div class="container moody">
  <div class="card">
    <div class="card-header">
      <h2 style="margin-top: 10px"><%= @category.name %></h2>
    <div class="btn-div" style="margin-top: 5px">
      <%= link_to "Back to Categories", categories_path, class: "btn btn-outline-secondary float-right" %> 
      <%= link_to "Delete Category", category_path(@category), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger float-right" %></div>
    </div>
    <div class="card-body">
      <div class="card-container">
        <%= render partial: 'bookmarks/bookmark', collection: @category.bookmarks %>
      </div>
    </div>
    <div class="card-footer">
      <%= link_to 'New Bookmark', new_category_bookmark_path(@category), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cookbook List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>